const CACHE_NAME = 'twbtd-i22-portrait-static-a4-v1-2026-08-08';
const ART_CACHE_NAME = 'twbtd-portrait-static-runtime-a4-v1';
const MAX_RUNTIME_ART_ENTRIES = 180;
const STATIC_FILES = [
  './',
  './index.html',
  './styles.css',
  './manifest.webmanifest',
  './.nojekyll',
  './src/ability-controller.js',
  './src/account-bootstrap.js',
  './src/ally-ai.js',
  './src/app.js',
  './src/base-class-state.js',
  './src/campaign-controller.js',
  './src/campaign-door.js',
  './src/canon-registry.js',
  './src/character-creator.js',
  './src/character-progression.js',
  './src/chronicle-controller.js',
  './src/classless-controller.js',
  './src/combat-controller.js',
  './src/combat-math.js',
  './src/combat-presentation.js',
  './src/combat-resolution.js',
  './src/constants.js',
  './src/consumable-controller.js',
  './src/crafting-controller.js',
  './src/enemy-ai.js',
  './src/equipment-ability-controller.js',
  './src/equipment-controller.js',
  './src/expedition-controller.js',
  './src/forest-encounter-builder.js',
  './src/forest-event-controller.js',
  './src/forest-event-deck.js',
  './src/forest-reward-controller.js',
  './src/kept-impression-controller.js',
  './src/kept-impression-runtime.js',
  './src/kept-impression-state.js',
  './src/mantle-controller.js',
  './src/player-facing.js',
  './src/portrait-controller.js',
  './src/progression-features.js',
  './src/router.js',
  './src/save-controller.js',
  './src/starting-stats.js',
  './src/status-engine.js',
  './src/subclass-controller.js',
  './src/subclass-state.js',
  './src/tavern-controller.js',
  './src/tavern-services-controller.js',
  './src/tutorial-controller.js',
  './src/vessel-controller.js',
  './src/views/campaign-prep.js',
  './src/views/campaign-results.js',
  './src/views/campaign-run.js',
  './src/views/chronicle.js',
  './src/views/create-character.js',
  './src/views/credits.js',
  './src/views/help.js',
  './src/views/home.js',
  './src/views/portrait.js',
  './src/views/settings.js',
  './src/views/shared.js',
  './src/views/slots.js',
  './src/views/tavern.js',
  './src/views/tutorial.js',
  './data/account-bootstrap.json',
  './data/base-abilities.json',
  './data/base-class-resources.json',
  './data/canon-authority.json',
  './data/character-progression.json',
  './data/chronicle-trees-canon.txt',
  './data/chronicle-trees.json',
  './data/classless-chronicle-canon.txt',
  './data/combat-rules.json',
  './data/equipment-consumables-status.json',
  './data/forest-crafting.json',
  './data/forest-enemies.json',
  './data/forest-events.json',
  './data/forest-trainers.json',
  './data/kept-impression-runtime.json',
  './data/kept-impressions.json',
  './data/portrait-system.json',
  './data/regions.json',
  './data/starting-stats.json',
  './data/subclass-abilities.json',
  './data/tavern-adventurers.json',
  './data/tavern-services.json',
  './data/tutorials-help.json',
  './assets/combat/deep-rootway.svg',
  './assets/combat/forest-clearing.svg',
  './assets/combat/fungal-grove.svg',
  './assets/combat/heartwood-sanctum.svg',
  './assets/combat/mossed-path.svg',
  './assets/combat/thorn-hollow.svg',
  './assets/combat/trainer-glade.svg',
  './assets/icons/favicon.png',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/portraits/adventurers/guest-brakka.png',
  './assets/portraits/adventurers/guest-briar.png',
  './assets/portraits/adventurers/guest-dane.png',
  './assets/portraits/adventurers/guest-elowen.png',
  './assets/portraits/adventurers/guest-kethravel.png',
  './assets/portraits/adventurers/guest-mercury.png',
  './assets/portraits/adventurers/guest-nib.png',
  './assets/portraits/adventurers/guest-rill.png',
  './assets/portraits/adventurers/guest-sera.png',
  './assets/portraits/adventurers/guest-sparkscale.png',
  './assets/portraits/adventurers/guest-tawny.png',
  './assets/portraits/adventurers/guest-unit-seven.png',
  './assets/portraits/adventurers/guest-vesper.png',
  './assets/portraits/enemies/barkveil-sapper.png',
  './assets/portraits/enemies/bramblekin-scrapper.png',
  './assets/portraits/enemies/chimeleaf-wisp.png',
  './assets/portraits/enemies/crown-of-thorns-warden.png',
  './assets/portraits/enemies/glasswing-needler.png',
  './assets/portraits/enemies/gloomcap-binder.png',
  './assets/portraits/enemies/heartwood-sovereign.png',
  './assets/portraits/enemies/ironbark-ram.png',
  './assets/portraits/enemies/mossjaw-boar.png',
  './assets/portraits/enemies/needlefang-lynx.png',
  './assets/portraits/enemies/rootcoil-hexer.png',
  './assets/portraits/enemies/sporecap-tender.png',
  './assets/portraits/enemies/sunscar-hart.png',
  './assets/portraits/enemies/vinebound-reaver.png',
  './assets/portraits/vessels/adaptedfist/female-01.png',
  './assets/portraits/vessels/adaptedfist/female-02.png',
  './assets/portraits/vessels/adaptedfist/female-03.png',
  './assets/portraits/vessels/adaptedfist/male-01.png',
  './assets/portraits/vessels/adaptedfist/male-02.png',
  './assets/portraits/vessels/adaptedfist/male-03.png',
  './assets/portraits/vessels/barkmorph/female-01.png',
  './assets/portraits/vessels/barkmorph/female-02.png',
  './assets/portraits/vessels/barkmorph/female-03.png',
  './assets/portraits/vessels/barkmorph/male-01.png',
  './assets/portraits/vessels/barkmorph/male-02.png',
  './assets/portraits/vessels/barkmorph/male-03.png',
  './assets/portraits/vessels/belowcaller/female-01.png',
  './assets/portraits/vessels/belowcaller/female-02.png',
  './assets/portraits/vessels/belowcaller/female-03.png',
  './assets/portraits/vessels/belowcaller/male-01.png',
  './assets/portraits/vessels/belowcaller/male-02.png',
  './assets/portraits/vessels/belowcaller/male-03.png',
  './assets/portraits/vessels/bloodknuckle/female-01.png',
  './assets/portraits/vessels/bloodknuckle/female-02.png',
  './assets/portraits/vessels/bloodknuckle/female-03.png',
  './assets/portraits/vessels/bloodknuckle/male-01.png',
  './assets/portraits/vessels/bloodknuckle/male-02.png',
  './assets/portraits/vessels/bloodknuckle/male-03.png',
  './assets/portraits/vessels/brandblade/female-01.png',
  './assets/portraits/vessels/brandblade/female-02.png',
  './assets/portraits/vessels/brandblade/female-03.png',
  './assets/portraits/vessels/brandblade/male-01.png',
  './assets/portraits/vessels/brandblade/male-02.png',
  './assets/portraits/vessels/brandblade/male-03.png',
  './assets/portraits/vessels/breachstrider/female-01.png',
  './assets/portraits/vessels/breachstrider/female-02.png',
  './assets/portraits/vessels/breachstrider/female-03.png',
  './assets/portraits/vessels/breachstrider/male-01.png',
  './assets/portraits/vessels/breachstrider/male-02.png',
  './assets/portraits/vessels/breachstrider/male-03.png',
  './assets/portraits/vessels/cadenceblade/female-01.png',
  './assets/portraits/vessels/cadenceblade/female-02.png',
  './assets/portraits/vessels/cadenceblade/female-03.png',
  './assets/portraits/vessels/cadenceblade/male-01.png',
  './assets/portraits/vessels/cadenceblade/male-02.png',
  './assets/portraits/vessels/cadenceblade/male-03.png',
  './assets/portraits/vessels/choruswarden/female-01.png',
  './assets/portraits/vessels/choruswarden/female-02.png',
  './assets/portraits/vessels/choruswarden/female-03.png',
  './assets/portraits/vessels/choruswarden/male-01.png',
  './assets/portraits/vessels/choruswarden/male-02.png',
  './assets/portraits/vessels/choruswarden/male-03.png',
  './assets/portraits/vessels/dawnwarden/female-01.png',
  './assets/portraits/vessels/dawnwarden/female-02.png',
  './assets/portraits/vessels/dawnwarden/female-03.png',
  './assets/portraits/vessels/dawnwarden/male-01.png',
  './assets/portraits/vessels/dawnwarden/male-02.png',
  './assets/portraits/vessels/dawnwarden/male-03.png',
  './assets/portraits/vessels/dreadcantor/female-01.png',
  './assets/portraits/vessels/dreadcantor/female-02.png',
  './assets/portraits/vessels/dreadcantor/female-03.png',
  './assets/portraits/vessels/dreadcantor/male-01.png',
  './assets/portraits/vessels/dreadcantor/male-02.png',
  './assets/portraits/vessels/dreadcantor/male-03.png',
  './assets/portraits/vessels/duelist/female-01.png',
  './assets/portraits/vessels/duelist/female-02.png',
  './assets/portraits/vessels/duelist/female-03.png',
  './assets/portraits/vessels/duelist/male-01.png',
  './assets/portraits/vessels/duelist/male-02.png',
  './assets/portraits/vessels/duelist/male-03.png',
  './assets/portraits/vessels/fluxwrought/female-01.png',
  './assets/portraits/vessels/fluxwrought/female-02.png',
  './assets/portraits/vessels/fluxwrought/female-03.png',
  './assets/portraits/vessels/fluxwrought/male-01.png',
  './assets/portraits/vessels/fluxwrought/male-02.png',
  './assets/portraits/vessels/fluxwrought/male-03.png',
  './assets/portraits/vessels/fontborn/female-01.png',
  './assets/portraits/vessels/fontborn/female-02.png',
  './assets/portraits/vessels/fontborn/female-03.png',
  './assets/portraits/vessels/fontborn/male-01.png',
  './assets/portraits/vessels/fontborn/male-02.png',
  './assets/portraits/vessels/fontborn/male-03.png',
  './assets/portraits/vessels/glyphmorpher/female-01.png',
  './assets/portraits/vessels/glyphmorpher/female-02.png',
  './assets/portraits/vessels/glyphmorpher/female-03.png',
  './assets/portraits/vessels/glyphmorpher/male-01.png',
  './assets/portraits/vessels/glyphmorpher/male-02.png',
  './assets/portraits/vessels/glyphmorpher/male-03.png',
  './assets/portraits/vessels/gunslinger/female-01.png',
  './assets/portraits/vessels/gunslinger/female-02.png',
  './assets/portraits/vessels/gunslinger/female-03.png',
  './assets/portraits/vessels/gunslinger/male-01.png',
  './assets/portraits/vessels/gunslinger/male-02.png',
  './assets/portraits/vessels/gunslinger/male-03.png',
  './assets/portraits/vessels/hyphaweaver/female-01.png',
  './assets/portraits/vessels/hyphaweaver/female-02.png',
  './assets/portraits/vessels/hyphaweaver/female-03.png',
  './assets/portraits/vessels/hyphaweaver/male-01.png',
  './assets/portraits/vessels/hyphaweaver/male-02.png',
  './assets/portraits/vessels/hyphaweaver/male-03.png',
  './assets/portraits/vessels/longwatch/female-01.png',
  './assets/portraits/vessels/longwatch/female-02.png',
  './assets/portraits/vessels/longwatch/female-03.png',
  './assets/portraits/vessels/longwatch/male-01.png',
  './assets/portraits/vessels/longwatch/male-02.png',
  './assets/portraits/vessels/longwatch/male-03.png',
  './assets/portraits/vessels/lumenwrath/female-01.png',
  './assets/portraits/vessels/lumenwrath/female-02.png',
  './assets/portraits/vessels/lumenwrath/female-03.png',
  './assets/portraits/vessels/lumenwrath/male-01.png',
  './assets/portraits/vessels/lumenwrath/male-02.png',
  './assets/portraits/vessels/lumenwrath/male-03.png',
  './assets/portraits/vessels/malisunder/female-01.png',
  './assets/portraits/vessels/malisunder/female-02.png',
  './assets/portraits/vessels/malisunder/female-03.png',
  './assets/portraits/vessels/malisunder/male-01.png',
  './assets/portraits/vessels/malisunder/male-02.png',
  './assets/portraits/vessels/malisunder/male-03.png',
  './assets/portraits/vessels/mortisworn/female-01.png',
  './assets/portraits/vessels/mortisworn/female-02.png',
  './assets/portraits/vessels/mortisworn/female-03.png',
  './assets/portraits/vessels/mortisworn/male-01.png',
  './assets/portraits/vessels/mortisworn/male-02.png',
  './assets/portraits/vessels/mortisworn/male-03.png',
  './assets/portraits/vessels/prismatic-palm/female-01.png',
  './assets/portraits/vessels/prismatic-palm/female-02.png',
  './assets/portraits/vessels/prismatic-palm/female-03.png',
  './assets/portraits/vessels/prismatic-palm/male-01.png',
  './assets/portraits/vessels/prismatic-palm/male-02.png',
  './assets/portraits/vessels/prismatic-palm/male-03.png',
  './assets/portraits/vessels/pyrecovenant/female-01.png',
  './assets/portraits/vessels/pyrecovenant/female-02.png',
  './assets/portraits/vessels/pyrecovenant/female-03.png',
  './assets/portraits/vessels/pyrecovenant/male-01.png',
  './assets/portraits/vessels/pyrecovenant/male-02.png',
  './assets/portraits/vessels/pyrecovenant/male-03.png',
  './assets/portraits/vessels/ruinhewer/female-01.png',
  './assets/portraits/vessels/ruinhewer/female-02.png',
  './assets/portraits/vessels/ruinhewer/female-03.png',
  './assets/portraits/vessels/ruinhewer/male-01.png',
  './assets/portraits/vessels/ruinhewer/male-02.png',
  './assets/portraits/vessels/ruinhewer/male-03.png',
  './assets/portraits/vessels/sealweaver/female-01.png',
  './assets/portraits/vessels/sealweaver/female-02.png',
  './assets/portraits/vessels/sealweaver/female-03.png',
  './assets/portraits/vessels/sealweaver/male-01.png',
  './assets/portraits/vessels/sealweaver/male-02.png',
  './assets/portraits/vessels/sealweaver/male-03.png',
  './assets/portraits/vessels/seedmarshal/female-01.png',
  './assets/portraits/vessels/seedmarshal/female-02.png',
  './assets/portraits/vessels/seedmarshal/female-03.png',
  './assets/portraits/vessels/seedmarshal/male-01.png',
  './assets/portraits/vessels/seedmarshal/male-02.png',
  './assets/portraits/vessels/seedmarshal/male-03.png',
  './assets/portraits/vessels/solaceweaver/female-01.png',
  './assets/portraits/vessels/solaceweaver/female-02.png',
  './assets/portraits/vessels/solaceweaver/female-03.png',
  './assets/portraits/vessels/solaceweaver/male-01.png',
  './assets/portraits/vessels/solaceweaver/male-02.png',
  './assets/portraits/vessels/solaceweaver/male-03.png',
  './assets/portraits/vessels/spellconductor/female-01.png',
  './assets/portraits/vessels/spellconductor/female-02.png',
  './assets/portraits/vessels/spellconductor/female-03.png',
  './assets/portraits/vessels/spellconductor/male-01.png',
  './assets/portraits/vessels/spellconductor/male-02.png',
  './assets/portraits/vessels/spellconductor/male-03.png',
  './assets/portraits/vessels/spellflare/female-01.png',
  './assets/portraits/vessels/spellflare/female-02.png',
  './assets/portraits/vessels/spellflare/female-03.png',
  './assets/portraits/vessels/spellflare/male-01.png',
  './assets/portraits/vessels/spellflare/male-02.png',
  './assets/portraits/vessels/spellflare/male-03.png',
  './assets/portraits/vessels/steelbearer/female-01.png',
  './assets/portraits/vessels/steelbearer/female-02.png',
  './assets/portraits/vessels/steelbearer/female-03.png',
  './assets/portraits/vessels/steelbearer/male-01.png',
  './assets/portraits/vessels/steelbearer/male-02.png',
  './assets/portraits/vessels/steelbearer/male-03.png',
  './assets/portraits/vessels/trailguard/female-01.png',
  './assets/portraits/vessels/trailguard/female-02.png',
  './assets/portraits/vessels/trailguard/female-03.png',
  './assets/portraits/vessels/trailguard/male-01.png',
  './assets/portraits/vessels/trailguard/male-02.png',
  './assets/portraits/vessels/trailguard/male-03.png',
  './assets/portraits/vessels/veil-blade/female-01.png',
  './assets/portraits/vessels/veil-blade/female-02.png',
  './assets/portraits/vessels/veil-blade/female-03.png',
  './assets/portraits/vessels/veil-blade/male-01.png',
  './assets/portraits/vessels/veil-blade/male-02.png',
  './assets/portraits/vessels/veil-blade/male-03.png',
  './assets/portraits/vessels/verdictbearer/female-01.png',
  './assets/portraits/vessels/verdictbearer/female-02.png',
  './assets/portraits/vessels/verdictbearer/female-03.png',
  './assets/portraits/vessels/verdictbearer/male-01.png',
  './assets/portraits/vessels/verdictbearer/male-02.png',
  './assets/portraits/vessels/verdictbearer/male-03.png',
  './assets/portraits/vessels/vowscarred/female-01.png',
  './assets/portraits/vessels/vowscarred/female-02.png',
  './assets/portraits/vessels/vowscarred/female-03.png',
  './assets/portraits/vessels/vowscarred/male-01.png',
  './assets/portraits/vessels/vowscarred/male-02.png',
  './assets/portraits/vessels/vowscarred/male-03.png',
  './assets/route-art/combat.svg',
  './assets/route-art/discovery.svg',
  './assets/route-art/event.svg',
  './assets/route-art/helpful-person.svg',
  './assets/route-art/landmark.svg',
  './assets/route-art/trainer.svg'
];

function isRuntimeVesselPortrait(url){
  return /\/assets\/portraits\/vessels-static\//.test(url.pathname);
}

async function trimRuntimeArt(cache){
  const keys=await cache.keys();
  const excess=keys.length-MAX_RUNTIME_ART_ENTRIES;
  if(excess>0)await Promise.all(keys.slice(0,excess).map(request=>cache.delete(request)));
}

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(STATIC_FILES)));
  self.skipWaiting();
});

self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('twbtd-') && k !== CACHE_NAME && k !== ART_CACHE_NAME).map(k => caches.delete(k)))));
  self.clients.claim();
});

async function safeNetwork(request,cacheName=CACHE_NAME) {
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      const cache = await caches.open(cacheName);
      await cache.put(request, response.clone());
      if(cacheName===ART_CACHE_NAME)await trimRuntimeArt(cache);
    }
    return response;
  } catch (_error) {
    return null;
  }
}

async function runtimePortraitResponse(request){
  const cache=await caches.open(ART_CACHE_NAME);
  const cached=await cache.match(request);
  if(cached)return cached;
  return (await safeNetwork(request,ART_CACHE_NAME)) || new Response('Offline portrait unavailable until it has been viewed once.', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const network = await safeNetwork(request);
      if (network) return network;
      return (await caches.match('./index.html')) || new Response('TWBTD is offline and the app shell is unavailable.', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
    })());
    return;
  }

  if(isRuntimeVesselPortrait(url)){event.respondWith(runtimePortraitResponse(request));return;}
  event.respondWith(caches.match(request).then(cached => cached || safeNetwork(request).then(network => network || new Response('Offline asset unavailable.', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }))));
});
