import {escapeHtml,shell} from './shared.js';
export function renderTutorial({tutorial,stepIndex=0,replay=true,status='never-seen'}){
  if(!tutorial)return shell('<section class="panel"><h2>Tutorial unavailable</h2><p class="muted">That lesson could not be opened.</p></section>',{back:true,backAction:'tutorial-exit',backLabel:'Exit Tutorial'});
  const steps=tutorial.steps||[];const index=Math.max(0,Math.min(Number(stepIndex||0),Math.max(0,steps.length-1)));const step=steps[index]||{};const last=index>=steps.length-1;
  return shell(`<section class="tutorial-stage panel" data-tutorial-id="${escapeHtml(tutorial.id)}"><div class="kicker">${replay?'Training Chamber Replay':'Guided Lesson'}</div><h2>${escapeHtml(tutorial.name)}</h2><div class="tutorial-progress"><span>Step ${index+1} of ${steps.length}</span><div class="progress-track"><div class="progress-fill" style="width:${steps.length?((index+1)/steps.length*100):100}%"></div></div></div><article class="tutorial-focus section"><div class="tutorial-arrow" aria-hidden="true">↓</div><h3>${escapeHtml(step.title||'Lesson')}</h3><p>${escapeHtml(step.body||'')}</p></article><div class="tutorial-actions section"><button class="secondary" data-action="tutorial-skip">Skip Tutorial</button>${index>0?'<button class="secondary" data-action="tutorial-prev">Back</button>':''}${last?'':'<button class="secondary" data-action="tutorial-next">Skip Step</button>'}<button class="primary" data-action="${last?'tutorial-complete':'tutorial-next'}">${last?'Complete':'Next'}</button></div><p class="field-help">Replay lessons are isolated from campaign resources and never grant additional starter rewards. Current status: ${escapeHtml(status)}.</p></section>`,{back:true,backAction:'tutorial-exit',backLabel:'Exit Tutorial'});
}
export function starterTutorialOverlay({starter,stepIndex=0}){const steps=starter?.steps||[];const index=Math.max(0,Math.min(Number(stepIndex||0),Math.max(0,steps.length-1)));const step=steps[index]||{};const last=index>=steps.length-1;return `<div class="tutorial-gate" role="dialog" aria-modal="true" aria-labelledby="starter-title"><section class="tutorial-gate-card"><div class="kicker">Starter Tutorial</div><h2 id="starter-title">${escapeHtml(starter?.name||'First Steps')}</h2><div class="tutorial-progress"><span>Step ${index+1} of ${steps.length}</span><div class="progress-track"><div class="progress-fill" style="width:${steps.length?((index+1)/steps.length*100):100}%"></div></div></div><article class="tutorial-focus section"><h3>${escapeHtml(step.title||'Welcome')}</h3><p>${escapeHtml(step.body||'')}</p></article><div class="notice section"><strong>One-time starter reward:</strong> 2 free Kept Impression tokens, each redeemable for an Impression costing 3 slots or less. You receive them whether you complete or skip this starter lesson.</div><div class="tutorial-actions section"><button class="secondary" data-action="starter-skip">Skip Tutorial & Receive Tokens</button>${index>0?'<button class="secondary" data-action="starter-prev">Back</button>':''}<button class="primary" data-action="${last?'starter-complete':'starter-next'}">${last?'Finish & Receive Tokens':'Next'}</button></div></section></div>`;}

export function guidedTutorialOverlay({tutorial,stepIndex=0}){const steps=tutorial?.steps||[];const index=Math.max(0,Math.min(Number(stepIndex||0),Math.max(0,steps.length-1)));const step=steps[index]||{};const last=index>=steps.length-1;return `<div class="guided-tutorial-overlay" role="dialog" aria-modal="false" aria-label="${escapeHtml(tutorial?.name||'Tutorial')}"><div class="kicker">Guided Tutorial · ${index+1}/${steps.length}</div><strong>${escapeHtml(step.title||tutorial?.name||'Lesson')}</strong><p>${escapeHtml(step.body||'')}</p><div class="tutorial-actions"><button class="secondary" data-action="guided-tutorial-skip">Skip For Now</button>${index>0?'<button class="secondary" data-action="guided-tutorial-prev">Back</button>':''}${last?'':'<button class="secondary" data-action="guided-tutorial-next">Skip Step</button>'}<button class="primary" data-action="${last?'guided-tutorial-complete':'guided-tutorial-next'}">${last?'Complete':'Next'}</button></div></div>`;}
