import { BASE_MAX_ENERGY } from './combat-math.js';
import { commitResolvedAiAction, endCombatTurn, getCombatActor } from './combat-controller.js';
import { chooseDruidStartingForm, executeBaseAbility, listUsableBaseAbilities } from './ability-controller.js';
import { executeSubclassAbility, listUsableSubclassAbilities } from './subclass-controller.js';

function clone(v){return typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));}
function alive(a){return Number(a?.resources?.hp||0)>0;}
function hpPct(a){return Number(a?.resources?.maxHp||0)>0?Number(a.resources.hp||0)/Number(a.resources.maxHp)*100:0;}
function effectNegative(a){return (a.effects||[]).some(e=>e.negative);}
function allies(combat,actor){return (combat.actors||[]).filter(a=>a.side===actor.side&&alive(a));}
function enemies(combat,actor){return (combat.actors||[]).filter(a=>a.side!==actor.side&&alive(a));}
function lowestHp(list){return [...list].sort((a,b)=>hpPct(a)-hpPct(b)||a.id.localeCompare(b.id))[0]||null;}
function highestHp(list){return [...list].sort((a,b)=>hpPct(b)-hpPct(a)||b.resources.maxHp-a.resources.maxHp||a.id.localeCompare(b.id))[0]||null;}
function lowestAbsoluteHp(list){return [...list].sort((a,b)=>Number(a.resources.hp)-Number(b.resources.hp)||a.id.localeCompare(b.id))[0]||null;}
function chooseEnemy(combat,actor){const list=enemies(combat,actor);const p=String(actor.priority||'').toLowerCase();if(p.includes('weakest'))return lowestAbsoluteHp(list);if(p.includes('strongest'))return highestHp(list);if(p.includes('exploit'))return list.find(effectNegative)||lowestAbsoluteHp(list);return lowestAbsoluteHp(list)||list[0]||null;}
function componentKinds(a){return new Set((a.components||[]).map(c=>c.type));}
function scoreAbility(ability,combat,actor,{subclass=false}={}){const kinds=componentKinds(ability);const p=String(actor.priority||'').toLowerCase();const personality=String(actor.personality||'').toLowerCase();const role=String(actor.combatRole||'').toLowerCase();let score=subclass?7:0;
  if(kinds.has('damage'))score+=20+Number(ability.energyCost||0)*2;
  if(kinds.has('heal')){const wounded=lowestHp(allies(combat,actor));score+=(wounded&&hpPct(wounded)<80)?50:5;if(p.includes('heal'))score+=35;if(role.includes('heal'))score+=25;}
  if(kinds.has('shield')){const wounded=lowestHp(allies(combat,actor));score+=(wounded&&hpPct(wounded)<75)?35:8;if(p.includes('protect'))score+=30;if(role.includes('protect')||role.includes('defend'))score+=20;}
  if(!kinds.size)score+=role.includes('support')||p.includes('protect')?24:10;
  if(p.includes('burst'))score+=Number(ability.energyCost||0)*4;if(p.includes('control')&&(ability.special||[]).length)score+=20;if(p.includes('conserve'))score-=Number(ability.energyCost||0)*5;
  if(personality.includes('reckless')&&kinds.has('damage'))score+=15;if(personality.includes('compassionate')&&(kinds.has('heal')||kinds.has('shield')))score+=15;if(personality.includes('cautious')&&(kinds.has('heal')||kinds.has('shield')))score+=8;
  const protective=new Set(['Trailguard','SteelBearer','Dawnwarden','Solaceweaver','Choruswarden','Seedmarshal']);const aggressive=new Set(['Ruinhewer','Veil Blade','Gunslinger','Spellflare','Lumenwrath','Longwatch','Dreadcantor','Fontborn','Verdictbearer','Cadenceblade']);
  if(protective.has(actor.subclass)&&(kinds.has('heal')||kinds.has('shield')||!kinds.size))score+=12;if(aggressive.has(actor.subclass)&&kinds.has('damage'))score+=12;return score;
}
function targetsFor(ability,combat,actor){const friendly=allies(combat,actor),hostile=enemies(combat,actor),target=chooseEnemy(combat,actor);if(ability.targetMode==='single-enemy')return {primary:target?.id||null};if(ability.targetMode==='single-ally'){const other=friendly.filter(a=>a.id!==actor.id);return {primary:(lowestHp(other)||lowestHp(friendly))?.id||null};}if(ability.targetMode==='ally-or-self')return {primary:lowestHp(friendly)?.id||actor.id};if(ability.targetMode==='two-allies'){const low=lowestHp(friendly)||actor,other=friendly.filter(a=>a.id!==low.id);return {heal:low.id,shield:(lowestHp(other)||low).id};}return {primary:target?.id||hostile[0]?.id||null};}
function choicesFor(ability,combat,actor){if(ability.name==='Quickscript')return {glyphs:['Edge','Echo']};if(ability.name==='Refract Stance')return {facetDirection:1};if(ability.name==='Probability Shear')return {fluxDirection:1};if(ability.name==='Mark Safe Ground')return {allyIds:allies(combat,actor).slice(0,2).map(a=>a.id)};return {};}
function defaultDruidForm(actor){const role=String(actor.combatRole||'').toLowerCase(),p=String(actor.priority||'').toLowerCase();if(role.includes('heal')||p.includes('heal'))return 'Bloom';if(role.includes('protect')||role.includes('defend')||p.includes('protect'))return 'Grove';return 'Fang';}
export function chooseTavernAdventurerAction(slot,{baseCatalog,subclassCatalog}={}){const combat=slot?.campaign?.state?.combat,actor=getCombatActor(combat,combat?.currentActorId);if(!actor||actor.control!=='ai'||actor.side!=='party'||actor.kind!=='tavern-adventurer'||!alive(actor))return {type:'none'};
  const base=listUsableBaseAbilities(combat,actor.id,baseCatalog).filter(a=>a.cooldownRemaining===0&&a.effectiveEnergyCost<=Number(actor.resources.energy||0)&&a.resourceRequired<=a.resourceAvailable).map(a=>({kind:'base',ability:a,score:scoreAbility(a,combat,actor)}));
  const sub=listUsableSubclassAbilities(combat,actor.id,subclassCatalog).filter(a=>a.cooldownRemaining===0&&a.effectiveEnergyCost<=Number(actor.resources.energy||0)&&a.resourceRequired<=a.resourceAvailable).map(a=>({kind:'subclass',ability:a,score:scoreAbility(a,combat,actor,{subclass:true})}));
  const scored=[...base,...sub].sort((a,b)=>b.score-a.score||Number(b.ability.energyCost)-Number(a.ability.energyCost)||a.ability.id.localeCompare(b.ability.id));if(scored.length&&scored[0].score>10)return {type:'ability',kind:scored[0].kind,ability:scored[0].ability,targets:targetsFor(scored[0].ability,combat,actor),choices:choicesFor(scored[0].ability,combat,actor)};
  const conserve=String(actor.priority||'').toLowerCase().includes('conserve');if(Number(actor.resources.energy||0)<Number(actor.resources.maxEnergy||BASE_MAX_ENERGY)&&(conserve||Number(actor.resources.energy||0)<2))return {type:'charge'};if(hpPct(actor)<=45||String(actor.priority||'').toLowerCase().includes('protect'))return {type:'guard'};if(scored.length)return {type:'ability',kind:scored[0].kind,ability:scored[0].ability,targets:targetsFor(scored[0].ability,combat,actor),choices:choicesFor(scored[0].ability,combat,actor)};return {type:Number(actor.resources.energy||0)<Number(actor.resources.maxEnergy||BASE_MAX_ENERGY)?'charge':'guard'};
}
export function executeTavernAdventurerAction(slot,{baseCatalog,subclassCatalog,rng=Math.random}={}){if(!slot?.campaign?.active||!slot.campaign.state?.combat)return {ok:false,error:'No active combat.'};let next=clone(slot),combat=next.campaign.state.combat,actor=getCombatActor(combat,combat.currentActorId);if(!actor||actor.control!=='ai'||actor.side!=='party'||actor.kind!=='tavern-adventurer')return {ok:false,error:'The current actor is not a Tavern Adventurer AI combatant.'};if(actor.classState?.baseClass==='Druid'&&!actor.classState?.form){const formResult=chooseDruidStartingForm(next,actor.id,defaultDruidForm(actor));if(formResult.ok){next=formResult.slot;combat=next.campaign.state.combat;actor=getCombatActor(combat,combat.currentActorId);}}
  const choice=chooseTavernAdventurerAction(next,{baseCatalog,subclassCatalog});if(choice.type==='ability'){const r=choice.kind==='subclass'?executeSubclassAbility(next,{abilityId:choice.ability.id,catalog:subclassCatalog,targets:choice.targets||{},choices:choice.choices||{},rng}):executeBaseAbility(next,{abilityId:choice.ability.id,catalog:baseCatalog,targets:choice.targets||{},rng});if(!r.ok)return r;return {ok:true,slot:r.slot,action:{type:'ability',kind:choice.kind,actorId:actor.id,abilityId:choice.ability.id}};}
  if(choice.type==='charge'){actor.resources.energy=Math.min(Number(actor.resources.maxEnergy||BASE_MAX_ENERGY),Number(actor.resources.energy||0)+1);const r=commitResolvedAiAction(next,{type:'charge',payload:{energyGained:1}});if(!r.ok)return r;return {ok:true,slot:r.slot,action:{type:'charge',actorId:actor.id}};}actor.defense.guardActive=true;const r=commitResolvedAiAction(next,{type:'guard',payload:null});if(!r.ok)return r;return {ok:true,slot:r.slot,action:{type:'guard',actorId:actor.id}};
}
export function resolveTavernAdventurerTurn(slot,{baseCatalog,subclassCatalog,rng=Math.random,now=new Date().toISOString()}={}){const acted=executeTavernAdventurerAction(slot,{baseCatalog,subclassCatalog,rng});if(!acted.ok)return acted;const ended=endCombatTurn(acted.slot,{now});if(!ended.ok)return ended;return {ok:true,slot:ended.slot,action:acted.action,outcome:ended.outcome||null};}
export function resolveConsecutivePartyAiTurns(slot,{baseCatalog,subclassCatalog,rng=Math.random,maxTurns=12}={}){let next=clone(slot),actions=[];for(let i=0;i<maxTurns;i++){const combat=next?.campaign?.state?.combat;if(!combat||combat.state==='complete')break;const actor=getCombatActor(combat,combat.currentActorId);if(!actor||actor.control!=='ai'||actor.side!=='party'||actor.kind!=='tavern-adventurer')break;const r=resolveTavernAdventurerTurn(next,{baseCatalog,subclassCatalog,rng});if(!r.ok)return r;next=r.slot;actions.push(r.action);}return {ok:true,slot:next,actions};}
