const LABELS={damageCritChancePct:'Crit Chance',criticalDamagePct:'Critical Damage',healingCritChancePct:'Healing Crit Chance',healingCriticalDamagePct:'Healing Critical Damage',blockChancePct:'Block Chance',blockedDamageReductionPct:'Blocked Damage Reduction',dodgeChancePct:'Dodge Chance',energyGainPct:'Energy Gain',incomingHealingPct:'Incoming Healing',outgoingHealingPct:'Outgoing Healing',finalDamagePct:'Final Damage',shieldStrengthPct:'Shield Strength',armorMitigationPct:'Armor Mitigation',initiativeBonus:'Initiative',aggroMultiplier:'Aggro Multiplier',STR:'STR',DEX:'DEX',CON:'CON',INT:'INT',FTH:'FTH',CHA:'CHA',LCK:'LCK'};
const SLOT_LABELS={mainHand:'Main Hand',offHand:'Off Hand',accessory:'Accessory',helmet:'Helmet',chest:'Chest Armor',boots:'Boots',gloves:'Gloves',charm:'Charm',charm1:'Charm 1',charm2:'Charm 2',abilityItem:'Ability Item',consumable:'Consumable'};
export function playerStatLabel(key=''){if(LABELS[key])return LABELS[key];return String(key).replace(/Pct$/,'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,m=>m.toUpperCase());}
export function formatStatBonus(key,value){const n=Number(value||0),sign=n>=0?'+':'';return `${playerStatLabel(key)} ${sign}${n}${String(key).endsWith('Pct')?'%':''}`;}
export function formatListedStats(item={}){const bits=[];for(const [k,v] of Object.entries(item.listedStats||{}))bits.push(formatStatBonus(k,v));for(const [k,v] of Object.entries(item.resistances||{}))bits.push(`${playerStatLabel(k)} Resistance +${Number(v||0)}%`);return bits.join(' · ')||'No listed stat bonuses';}
export function equipmentSlotLabel(itemOrSlot){if(typeof itemOrSlot==='string')return SLOT_LABELS[itemOrSlot]||playerStatLabel(itemOrSlot);const item=itemOrSlot||{};return SLOT_LABELS[item.slot]||item.itemType||'Equipment';}
export function itemTypeTag(item={}){if(item.itemType==='Weapon')return `${equipmentSlotLabel(item)} · ${item.weaponType||'Weapon'}`;if(item.itemType==='Armor')return `${equipmentSlotLabel(item)} · ${item.armorCategory||'Armor'}`;if(item.itemType==='Charm')return `Charm · ${item.charmType||'Trinket'}`;return `${equipmentSlotLabel(item)}${item.itemType&&item.itemType!==equipmentSlotLabel(item)?` · ${item.itemType}`:''}`;}
export function weaponCompatibilityText(item={},baseClass=null){if(item.itemType!=='Weapon')return '';const t=item.weaponType;if(baseClass==='Brawler'&&t!=='Gauntlet')return 'Incompatible: Brawler equips only Gauntlets.';if(baseClass==='Cleric'&&t==='Physical')return 'Incompatible: Cleric cannot equip Physical weapons.';if(['Mage','Warlock','Sorcerer'].includes(baseClass)&&t==='Physical')return 'Compatible with 80% of listed attribute/stat bonuses.';if(['Warrior','Paladin','Ranger'].includes(baseClass)&&t==='Magic')return 'Compatible with 80% of listed attribute/stat bonuses.';return baseClass?`Compatible with ${baseClass}.`:'Weapon compatibility follows class restrictions.';}
export function formatDerivedStats(stats={}){return Object.entries(stats).map(([k,v])=>`${playerStatLabel(k)} ${String(k)==='aggroMultiplier'?Number(v).toFixed(2)+'×':Number(v).toFixed(1)+(String(k).endsWith('Pct')?'%':'')}`).join(' · ');}
export function readableAbilityText(ability={}){
 const target=String(ability.targetMode||ability.target||'special').replaceAll('-',' ');
 const energy=Number(ability.effectiveEnergyCost??ability.energyCost??0), cooldown=Number(ability.cooldown??0);
 const components=(ability.components||[]).map(component=>{const kind=component.type==='damage'?`${component.damageType||'Damage'} damage`:component.type==='heal'?'Healing':component.type==='shield'?'Shield':playerStatLabel(component.type||'Effect');const base=Number(component.base||0);const scaling=Object.entries(component.scaling||{}).map(([key,value])=>`${playerStatLabel(key)} × ${Number(value)}`).join(' + ');return `${kind}: Base ${base}${scaling?` + ${scaling}`:''}`;});
 const resource=ability.resourceCost?`Resource cost: ${ability.resourceCost.amount} ${ability.resourceCost.resource}.`:'';
 const requirements=[];if(ability.requirements?.weaponType)requirements.push(`${ability.requirements.weaponType} weapon required`);if(Array.isArray(ability.requirements?.weaponTypes)&&ability.requirements.weaponTypes.length)requirements.push(`${ability.requirements.weaponTypes.join(' / ')} weapon required`);
 const canonical=String(ability.canonicalText||ability.canonical_text||ability.description||'').trim();
 return [`Level ${Number(ability.level||1)} · Energy cost ${energy} · Cooldown ${cooldown} · Target: ${target}.`,resource,requirements.length?`Requirements: ${requirements.join('; ')}.`:'',components.length?`Formula: ${components.join(' | ')}.`:'',canonical?`Effects / conditions: ${canonical}`:''].filter(Boolean).join('\n');
}
